/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package components.filepreview;

import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Random;
import net.sf.image4j.codec.ico.ICODecoder;
import net.sf.image4j.codec.ico.ICOImage;

/**
 *
 * @author Milo Steier
 */
public class ICOFileDetailsViewTester extends javax.swing.JFrame {

    /**
     * Creates new form Image4JFileDetailsViewTester
     */
    public ICOFileDetailsViewTester() {
        view = new ICOFileDetailsView();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fc = new javax.swing.JFileChooser();
        previewPanel = new components.JFileDisplayPanel();
        dialog = new javax.swing.JDialog();
        previewDialog = new components.JFileDisplayPanel();
        browseButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();
        showDialogButton = new javax.swing.JButton();
        detailsToggle = new javax.swing.JCheckBox();
        viewToggle = new javax.swing.JCheckBox();

        fc.setAccessory(previewPanel);

        previewPanel.setFileChooser(fc);
        previewPanel.setFileDetailsView(view);

        previewDialog.setFileChooser(fc);
        previewDialog.setFileDetailsView(view);

        javax.swing.GroupLayout dialogLayout = new javax.swing.GroupLayout(dialog.getContentPane());
        dialog.getContentPane().setLayout(dialogLayout);
        dialogLayout.setHorizontalGroup(
            dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(previewDialog, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        dialogLayout.setVerticalGroup(
            dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogLayout.createSequentialGroup()
                .addComponent(previewDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        browseButton.setText("Browse");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        printButton.setText("Print Data");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        showDialogButton.setText("Show Dialog");

        detailsToggle.setSelected(previewPanel.isShowingFileDetails());
        detailsToggle.setText("Show File Details");
        detailsToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsToggleActionPerformed(evt);
            }
        });

        viewToggle.setSelected(true);
        viewToggle.setText("Use Image4JView");
        viewToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewToggleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(detailsToggle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(viewToggle))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(browseButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(printButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(showDialogButton)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(browseButton)
                    .addComponent(printButton)
                    .addComponent(showDialogButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(detailsToggle)
                    .addComponent(viewToggle))
                .addContainerGap(228, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void detailsToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsToggleActionPerformed
        previewPanel.setShowingFileDetails(detailsToggle.isSelected());
        previewDialog.setShowingFileDetails(detailsToggle.isSelected());
    }//GEN-LAST:event_detailsToggleActionPerformed

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        System.out.println("Selected button: "+fc.showOpenDialog(null));
        System.out.println("Selected File: " + fc.getSelectedFile());
        System.out.println("Selected Files: " + Arrays.toString(fc.getSelectedFiles()));
        System.out.println("Displayed File: " + previewPanel.getDisplayedFile());
    }//GEN-LAST:event_browseButtonActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        System.out.println("Sorting List ICOImages Test:");
        File file = fc.getSelectedFile();
        System.out.println("File: " + file);
        if (file != null){
            try{
                List<ICOImage> images = ICODecoder.readExt(file);
                for (int i = 0; i < images.size(); i++){
                    System.out.println(images.get(i).getColourDepth() + " " + images.get(i).getImage().getWidth() + " x " + images.get(i).getImage().getHeight());
                }
                ArrayList<ICOImage> temp = new ArrayList<>(images);
                ArrayList<ICOImage> arr = new ArrayList<>();
                while (temp.size() > 1){
                    arr.add(temp.remove(rand.nextInt(temp.size())));
                }
                if (!temp.isEmpty())
                    arr.add(temp.remove(0));
                System.out.println();
                System.out.println("Randomized Order:");
                for (ICOImage arr1 : arr) {
                    System.out.println(arr1.getColourDepth() + " " + arr1.getImage().getWidth() + " x " + arr1.getImage().getHeight());
                }
                arr.sort(view.getIconImageComparator());
                System.out.println("Sorted order:");
                for (ICOImage arr1 : arr) {
                    System.out.println(arr1.getColourDepth() + " " + arr1.getImage().getWidth() + " x " + arr1.getImage().getHeight());
                }
            }
            catch(Exception ex){
                System.out.println("Error: " + ex);
            }
        }
    }//GEN-LAST:event_printButtonActionPerformed

    private void viewToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewToggleActionPerformed
        previewPanel.setFileDetailsView((viewToggle.isSelected()) ? view : null);
        previewDialog.setFileDetailsView((viewToggle.isSelected()) ? view : null);
    }//GEN-LAST:event_viewToggleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ICOFileDetailsViewTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ICOFileDetailsViewTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ICOFileDetailsViewTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ICOFileDetailsViewTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ICOFileDetailsViewTester().setVisible(true);
            }
        });
    }
    
    private ICOFileDetailsView view;
    private Random rand = new Random();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseButton;
    private javax.swing.JCheckBox detailsToggle;
    private javax.swing.JDialog dialog;
    private javax.swing.JFileChooser fc;
    private components.JFileDisplayPanel previewDialog;
    private components.JFileDisplayPanel previewPanel;
    private javax.swing.JButton printButton;
    private javax.swing.JButton showDialogButton;
    private javax.swing.JCheckBox viewToggle;
    // End of variables declaration//GEN-END:variables
}
